<?xml version="1.0"?>
<robot name="myagv_mecanum" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find myagv)/urdf/mecanum_properties.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/mech/mecanum_wheel.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/sensors/plugins.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find myagv)/urdf/controllers/omni_drive.urdf.xacro" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
  />

  <xacro:mecanum_wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:mecanum_wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  <xacro:mecanum_wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:mecanum_wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:imu/>
  
  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  

  <xacro:omni_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_base="${wheel_pos_x * 2}"
    wheel_radius="${wheel_radius}"
  />
</robot>